start/min make-host-4net_anzhi-mm7-all.bat
start/min make-host-4net_baidu-mm7-all.bat
start/min make-host-4net_uc-mm7-all.bat
start/min make-host-4net-4399_mm7-all.bat
start/min make-host-4net-bf-mm7-all.bat
start/min make-host-4net-huawei_mm7-all.bat
start/min make-host-4net-iqiyi_mm7-all.bat
start/min make-host-4net-kugou_mm7-all.bat
start/min make-host-4net-kuwo-mm7-all.bat
start/min make-host-4net-lenovo_mm7-all.bat