start/min makeSubPackage-4net-4399-ck-feiliujiutian-all.bat
start/min makeSubPackage-4net-4399-ck-ktoch-all.bat
start/min makeSubPackage-4net-4399-ck-chuandakeji-all.bat
start/min makeSubPackage-4net-4399-ck-zhuoyishichang-all.bat
start/min makeSubPackage-4net-4399-ck-qianchi-all.bat
start/min makeSubPackage-4net-4399-ck-fengxing-all.bat
start/min makeSubPackage-4net-4399-ck-litianbaoli-all.bat
start/min makeSubPackage-4net-4399-ck-coolpad-all.bat
start/min makeSubPackage-4net-4399-ck-7k7k-all.bat
start/min makeSubPackage-4net-4399-ck-Nduo-all.bat