start/min make-host-4net-yyb_ck-all.bat
start/min make-host-4net_qihoo-ck-all.bat
start/min make-host-4net-yyh_ck-all.bat
start/min make-host-4net-iqiyi_ck-all.bat
start/min make-host-4net_kugou-ck-all.bat
start/min make-host-4net-bf_ck-all.bat
start/min make-host-4net-youku_ck-all.bat
start/min make-host-4net-sina_ck-all.bat
start/min make-host-4net_huawei-ck-all.bat