start/min make-host-4net_anzhi-mm6-all.bat
start/min make-host-4net_baidu-mm6-all.bat
start/min make-host-4net_uc-mm6-all.bat
start/min make-host-4net-4399_mm6-all.bat
start/min make-host-4net-bf-mm6-all.bat
start/min make-host-4net-huawei_mm6-all.bat
start/min make-host-4net-iqiyi_mm6-all.bat
start/min make-host-4net-kugou_mm6-all.bat
start/min make-host-4net-kuwo-mm6-all.bat
start/min make-host-4net-lenovo_mm6-all.bat