call makeSubPackage-4net-4399-hai-albb-all.bat
call makeSubPackage-4net-4399-hai-dangle-all.bat
call makeSubPackage-4net-4399-hai-htc-all.bat
call makeSubPackage-4net-4399-hai-huawei-all.bat
call makeSubPackage-4net-4399-hai-jinli-all.bat
call makeSubPackage-4net-4399-hai-jiubang-all.bat
call makeSubPackage-4net-4399-hai-lemon-all.bat
call makeSubPackage-4net-4399-hai-lenovo-all.bat
call makeSubPackage-4net-4399-hai-meizu-all.bat
call makeSubPackage-4net-4399-hai-pptv-all.bat
call makeSubPackage-4net-4399-hai-sogouappshop-all.bat
call makeSubPackage-4net-4399-hai-sogoubrowser-all.bat
call makeSubPackage-4net-4399-hai-sogougame-all.bat
call makeSubPackage-4net-4399-hai-sogoushousuo-all.bat
call makeSubPackage-4net-4399-hai-sogoushurufa-all.bat
call makeSubPackage-4net-4399-hai-sogouzhushou-all.bat
call makeSubPackage-4net-4399-hai-wandoujia-all.bat
call makeSubPackage-4net-4399-hai-zhangmeng-all.bat